### ISSUE TITLE
Crash upon using 1.12 version. 

### ISSUE THREAD

**Issue by Akitori** [gigaherz/Ender-Rift#30]
Heya, i keep getting this crash here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 8/2/17 7:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender-Rift (enderrift)
Caused by: java.lang.NoClassDefFoundError: gigaherz/enderRift/shadow/common/BlockRegistered
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: gigaherz.enderRift.shadow.common.BlockRegistered
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 110937760 bytes (105 MB) / 360710144 bytes (344 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 Optifine OptiFine_1.12_HD_U_C4 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2420.jar) 
	UC	forge{14.21.1.2420} [Minecraft Forge] (forge-1.12-14.21.1.2420.jar) 
	UC	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UC	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.12-4.4.4.jar) 
	UC	antiqueatlasoverlay{1.2} [Antique Atlas Overlay] (antiqueatlas-1.12-4.4.4.jar) 
	UC	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UC	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UC	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UC	chickenchunks{2.4.0.70} [ChickenChunks] (ChickenChunks-1.12-2.4.0.70-universal.jar) 
	UC	cyclopscore{0.10.10} [Cyclops Core] (CyclopsCore-1.12-0.10.10.jar) 
	UC	colossalchests{1.6.5} [Colossal Chests] (ColossalChests-1.12-1.6.5.jar) 
	UE	enderrift{2.1.5} [Ender-Rift] (EnderRift-1.12.0-2.1.5.jar) 
	UC	foamflower{1.12-0.0.1.0} [Foamflower] (foamflower-1.12-0.0.1.0.jar) 
	UC	jei{4.7.1.75} [Just Enough Items] (jei_1.12-4.7.1.75.jar) 
	UC	forestry{5.5.0.154} [Forestry] (forestry_1.12-5.5.0.154.jar) 
	UC	immersiveengineering{0.12-70} [Immersive Engineering] (ImmersiveEngineering-0.12-70.jar) 
	UC	limelib{1.7.4} [LimeLib] (limelib-1.12-1.7.4.jar) 
	UC	modularrouters{1.12-3.0.0} [Modular Routers] (modular-routers-1.12-3.0.0.jar) 
	UC	particlespreader{1.2.0} [Particle Spreader] (particlespreader-1.12-1.2.0.jar) 
	UC	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UC	rafradek_tf2_weapons{1.1.10.1} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.12-1.1.10.1.jar) 
	UC	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UC	vending{1.12-2.0.0.0-beta2} [Vending] (vending-1.12-2.0.0.0-beta2.jar) 
	UC	vtweaks{1.4.11.3} [V-Tweaks] (VTweaks-1.12-1.4.11.3.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by zISKo666** [comment]
I got the same crash.

**Comment by gigaherz** [comment]
Thanks for the report! I'm looking into it.

**Comment by gigaherz** [comment]
It appears I had a typo in my build script which caused a library not to be included in the jar. I'll upload a bugfix in a minute.

**Comment by gigaherz** [comment]
v2.1.6 is under review at curseforge and will be available soon, sorry for the invoncenience!
