### ISSUE TITLE
Removing Modded Item Causes Crash

### ISSUE THREAD

**Issue by Rightfuldeathray** [gigaherz/Ender-Rift#40]
Removing an oak platform from the mod random things, from an ender rift via a rift browser causes my game to crash causes 

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/7/18 6:01 PM
Description: Ticking player

java.lang.IndexOutOfBoundsException: Index: 510, Size: 510
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at gigaherz.enderRift.automation.browser.ContainerBrowser$FakeInventoryServer.getStackInSlot(ContainerBrowser.java:694)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.inventory.Slot.func_75216_d(Slot.java:65)
	at com.rwtema.extrautils2.utils.datastructures.GetterSetter$ContainerSlot.get(GetterSetter.java:28)
	at com.rwtema.extrautils2.utils.datastructures.GetterSetter$ContainerSlot.get(GetterSetter.java:14)
	at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:201)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_714_ItemUnstableIngots_checkForExplosion_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at gigaherz.enderRift.automation.browser.ContainerBrowser$FakeInventoryServer.getStackInSlot(ContainerBrowser.java:694)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.inventory.Slot.func_75216_d(Slot.java:65)
	at com.rwtema.extrautils2.utils.datastructures.GetterSetter$ContainerSlot.get(GetterSetter.java:28)
	at com.rwtema.extrautils2.utils.datastructures.GetterSetter$ContainerSlot.get(GetterSetter.java:14)
	at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:201)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_714_ItemUnstableIngots_checkForExplosion_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 145
	Entity Name: Rightfuldeathray
	Entity's Exact location: 442.91, 72.00, 784.25
	Entity's Block location: World: (442,72,784), Chunk: (at 10,4,0 in 27,49; contains blocks 432,0,784 to 447,255,799), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@169b8d97
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2862836520 bytes (2730 MB) / 6471286784 bytes (6171 MB) up to 8879341568 bytes (8468 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9526m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2726 122 mods loaded, 122 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                             | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2726.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2726             | forge-1.12.2-14.23.4.2726.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | openmodscore                      | 0.11.5                   | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | uncraftingtable                   | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                          | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar             | None                                     |
	| UCHIJAAAA | libvulpes                         | 0.2.8.-32                | LibVulpes-1.12.2-0.2.8-32-universal.jar            | None                                     |
	| UCHIJAAAA | advancedrocketry                  | 1.4.0.-88                | AdvancedRocketry-1.12.2-1.4.0-88-universal.jar     | None                                     |
	| UCHIJAAAA | orbis_api                         | 1.12.2-1.1.5             | orbis_api-1.12.2-1.1.5.jar                         | None                                     |
	| UCHIJAAAA | aether                            | 1.12.2-1.0.8             | aether_ii-1.12.2-1.0.8.jar                         | None                                     |
	| UCHIJAAAA | aether_legacy                     | 1.12.2-v3.0              | aether_legacy-1.12.2-v3.0.jar                      | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCHIJAAAA | ctm                               | MC1.12.2-0.3.1.16        | CTM-MC1.12.2-0.3.1.16.jar                          | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                       | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.35            | EnderCore-1.12.2-0.5.35.jar                        | None                                     |
	| UCHIJAAAA | jei                               | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                          | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | brandonscore                      | 2.4.3                    | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
	| UCHIJAAAA | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalfoundation                 | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | draconicevolution                 | 2.3.12                   | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
	| UCHIJAAAA | thermalexpansion                  | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | enderio                           | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                           | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.7.6.jar                         | None                                     |
	| UCHIJAAAA | flyringbaublemod                  | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar        | None                                     |
	| UCHIJAAAA | applecore                         | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                       | None                                     |
	| UCHIJAAAA | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar              | None                                     |
	| UCHIJAAAA | psi                               | r1.1-59                  | Psi-r1.1-59.jar                                    | None                                     |
	| UCHIJAAAA | autoreglib                        | 1.3-18                   | AutoRegLib-1.3-18.jar                              | None                                     |
	| UCHIJAAAA | avaritia                          | 3.2.0                    | Avaritia-1.12.2-3.2.0.25-universal.jar             | None                                     |
	| UCHIJAAAA | avaritiatweaks                    | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAA | base                              | 3.9.0                    | base-1.12.2-3.9.0.jar                              | None                                     |
	| UCHIJAAAA | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
	| UCHIJAAAA | betterthanmending                 | 1.1.1                    | BetterThanMending-1.1.1.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| UCHIJAAAA | buildcraftlib                     | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftcore                    | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftbuilders                | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftenergy                  | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftfactory                 | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftrobotics                | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcrafttransport               | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | buildcraftsilicon                 | 7.99.17                  | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJAAAA | theoneprobe                       | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                        | None                                     |
	| UCHIJAAAA | buildcraftcompat                  | 7.99.14                  | buildcraft-compat-7.99.14.jar                      | None                                     |
	| UCHIJAAAA | chickenchunks                     | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | clumps                            | 3.1.1                    | Clumps-3.1.1.jar                                   | None                                     |
	| UCHIJAAAA | cyclopscore                       | 0.11.6                   | CyclopsCore-1.12.2-0.11.6.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | commoncapabilities                | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar                  | None                                     |
	| UCHIJAAAA | controlling                       | 3.0.6                    | Controlling-3.0.6.jar                              | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked             | 1.12.2-v1                | CosmeticArmorReworked-1.12.2-v1.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | cyberware                         | 0.2.10.12                | cyberware-1.12.2-0.2.10.12.jar                     | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAA | ptrmodellib                       | 1.0.2                    | PTRLib-1.0.2.jar                                   | None                                     |
	| UCHIJAAAA | props                             | 2.6.0                    | Decocraft-2.6.0_1.12.2.jar                         | None                                     |
	| UCHIJAAAA | diethopper                        | 1.1                      | diethopper-1.1.jar                                 | None                                     |
	| UCHIJAAAA | dldungeonsjdg                     | 1.11.1                   | DoomlikeDungeons-1.11.1-MC1.12.2.jar               | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderrift                         | 2.1.9                    | EnderRift-1.12.1-2.1.9.jar                         | None                                     |
	| UCHIJAAAA | enderstorage                      | 2.4.4.132                | EnderStorage-1.12.2-2.4.4.132-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | shetiphiancore                    | 3.5.7                    | shetiphiancore-1.12.0-3.5.7.jar                    | None                                     |
	| UCHIJAAAA | endertanks                        | 1.6.6                    | endertanks-1.12.0-1.6.6.jar                        | None                                     |
	| UCHIJAAAA | exponentialpower                  | 1.4.1                    | ExponentialPower-1.4.1.jar                         | None                                     |
	| UCHIJAAAA | extracells                        | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                    | None                                     |
	| UCHIJAAAA | shadowmc                          | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                            | None                                     |
	| UCHIJAAAA | extrarails                        | 1.3.0                    | ExtraRails-1.12-1.3.0.jar                          | None                                     |
	| UCHIJAAAA | forgelin                          | 1.7.4                    | Forgelin-1.7.4.jar                                 | None                                     |
	| UCHIJAAAA | geneticsreborn                    | 1.09                     | geneticsreborn-1.12-1.09.jar                       | None                                     |
	| UCHIJAAAA | healthhungertweaks                | 2.1.2                    | healthhungertweaks-1.12-2.1.2.jar                  | None                                     |
	| UCHIJAAAA | ichunutil                         | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| UCHIJAAAA | ironchest                         | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                    | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| UCHIJAAAA | jeresources                       | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
	| UCHIJAAAA | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
	| UCHIJAAAA | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| UCHIJAAAA | mcjtylib_ng                       | 3.0.2                    | mcjtylib-1.12-3.0.2.jar                            | None                                     |
	| UCHIJAAAA | mekanism                          | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
	| UCHIJAAAA | mekanismgenerators                | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
	| UCHIJAAAA | mekanismtools                     | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
	| UCHIJAAAA | moreoverlays                      | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                     | None                                     |
	| UCHIJAAAA | nonvflash                         | 1.2.0                    | NoNVFlash-1.12.2-1.2.0.3-universal.jar             | None                                     |
	| UCHIJAAAA | norecipebook                      | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
	| UCHIJAAAA | omlib                             | 3.0.0-148                | omlib-1.12.2-3.0.0-148.jar                         | None                                     |
	| UCHIJAAAA | ompd                              | 3.0.0-36                 | ompd-1.12.2-3.0.0-36.jar                           | None                                     |
	| UCHIJAAAA | openmods                          | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                        | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openmodularturrets                | 3.0.1-257                | openmodularturrets-1.12.2-3.0.1-257.jar            | None                                     |
	| UCHIJAAAA | placebo                           | 1.4.0                    | Placebo-1.12.2-1.4.0.jar                           | None                                     |
	| UCHIJAAAA | portalgun                         | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                         | None                                     |
	| UCHIJAAAA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                  | None                                     |
	| UCHIJAAAA | randomthings                      | 4.1.9                    | RandomThings-MC1.12.2-4.1.9.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | randomtweaks                      | 1.12.2-2.1.1.1           | randomtweaks-1.12.2-2.1.1.1.jar                    | None                                     |
	| UCHIJAAAA | xreliquary                        | 1.12.2-1.3.4.767         | Reliquary-1.12.2-1.3.4.767.jar                     | None                                     |
	| UCHIJAAAA | rewired                           | 1.12.2                   | ReWIRED-1.0.3.jar                                  | None                                     |
	| UCHIJAAAA | rftools                           | 7.54                     | rftools-1.12-7.54.jar                              | None                                     |
	| UCHIJAAAA | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| UCHIJAAAA | llibrary                          | 1.7.14                   | llibrary-1.7.14-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | rotd                              | 1.7.3                    | ROTD-1.12.2- 1.7.4.jar                             | None                                     |
	| UCHIJAAAA | scannable                         | 1.6.3.19                 | Scannable-MC1.12-1.6.3.19.jar                      | None                                     |
	| UCHIJAAAA | stairway                          | v08                      | Stairway_1.12_v08.jar                              | None                                     |
	| UCHIJAAAA | supersoundmuffler                 | 1.0.2.9                  | supersoundmuffler-1.12.1-1.0.2.9.jar               | None                                     |
	| UCHIJAAAA | thermaldynamics                   | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | toastcontrol                      | 1.7.0                    | Toast Control-1.12.2-1.7.0.jar                     | None                                     |
	| UCHIJAAAA | torchmaster                       | 1.6.4.62                 | torchmaster_1.12.2-1.6.4.62.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAAAA | torohealthmod                     | 1.12.2-11                | torohealth-1.12.2-11.jar                           | None                                     |
	| UCHIJAAAA | twilightforest                    | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar        | None                                     |
	| UCHIJAAAA | wanionlib                         | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                           | None                                     |
	| UCHIJAAAA | unidict                           | 1.12.2-2.5e              | UniDict-1.12.2-2.5e.jar                            | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.7.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Rightfuldeathray'/145, l='Let's Play a Game', x=442.91, y=72.00, z=784.25]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by gigaherz** [comment]
I will take a look as soon as I can, I sort of got sick again...
